name: ABC

on:
  workflow_call:
    outputs:
      envs:
        value: ${{ jobs.setenv.outputs.envs }}

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.encode.outputs.envs }}
    steps:
      - name: Set ENV
        id: "set"
        run: |
          tmpf=$(mktemp)

          cat <<EOT >> $tmpf

          PORT=3002
          APP_NAME=abc

          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          EOT

          echo "envs=$(echo $tmpf | base64)" >> $GITHUB_OUTPUT

      - uses: cloudposse/github-action-secret-outputs@main
        id: encode
        with:
          secret: "secret"
          op: encode
          in: ${{ steps.set.outputs.envs }}
