name: Deployment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying ${{ inputs.app-name }}"
