name: Deployment

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string

jobs:
  setenvs:
    uses: crgeary/secrets-workflow-demo/.github/workflows/apps/xyz.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs: setenvs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo "Deploying ${{ inputs.app-name }} with:"
          echo ${{ needs.setenvs.outputs.envs }} | base64 -d
