name: XYZ

on:
  workflow_call:
    outputs:
      envs:
        value: ${{ jobs.setenv.outputs.envs }}

jobs:
  setenv:
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.set.outputs.envs }}
    steps:
      - name: Set ENV
        id: "set"
        run: |
          echo "envs=abcxyz" >> $GITHUB_OUTPUT
